### ISSUE TITLE
Missing whitespace

### ISSUE THREAD

**Issue by stevepolitodesign** [andrewmcodes/personal-website#36] opened 2020-07-07 10:58 UTC
Some words are missing a whitespace.

- ![Screen Shot 2020-07-07 at 6 57 04 AM](https://user-images.githubusercontent.com/5122678/86770726-22e25980-c01f-11ea-8a00-ce67ed8e4fdf.png)
- ![Screen Shot 2020-07-07 at 6 56 45 AM](https://user-images.githubusercontent.com/5122678/86770727-22e25980-c01f-11ea-8062-0c6434ae8579.png)
- ![Screen Shot 2020-07-07 at 6 56 33 AM](https://user-images.githubusercontent.com/5122678/86770728-237af000-c01f-11ea-863a-041824406fba.png)
- ![Screen Shot 2020-07-07 at 6 56 30 AM](https://user-images.githubusercontent.com/5122678/86770729-237af000-c01f-11ea-9102-ab2d3482bd4f.png)
- ![Screen Shot 2020-07-07 at 6 56 22 AM](https://user-images.githubusercontent.com/5122678/86770730-237af000-c01f-11ea-8da5-d6bbac717f4b.png)

**Comment by matthewl** [comment] 2020-07-07 13:40
It looks like the styling for the anchor tags. The anchor tags in the hero section and background section have the spaces around them missing.

**Comment by andrewmcodes** [comment] 2020-07-21 12:19
Thanks @stevepolitodesign ❤️ 

Fixed in v2.

**Closed as completed by andrewmcodes** 2020-07-21 12:19 UTC

**Comment by andrewmcodes** [comment] 2020-07-21 14:52
@matthewl it was actually caused by a html compression plugin I was running via netlify. Turned it off and everything was fine!
